"""Parse every code cell in the notebook.

Needs no TensorFlow, so it runs anywhere:

    python -m tools.test_notebook_syntax

A broken string literal in a plot title once cost a full Colab run: the
experiments trained for twenty minutes and then the final cell raised
SyntaxError. The notebook is generated by tools/build_notebook.py, where cell
bodies are Python strings inside Python strings, so an escape that survives one
level and not the other produces exactly that. Parsing the generated cells
catches it in under a second.
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

NOTEBOOK = Path(__file__).resolve().parent.parent / "notebooks" / "mnist_neural_networks.ipynb"


def test_every_code_cell_parses() -> None:
    notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    cells = [c for c in notebook["cells"] if c["cell_type"] == "code"]
    assert cells, f"no code cells found in {NOTEBOOK}"

    failures = []
    for index, cell in enumerate(notebook["cells"]):
        if cell["cell_type"] != "code":
            continue
        source = "".join(cell["source"])
        # IPython magics and shell escapes are not Python; drop those lines.
        source = "\n".join(
            line
            for line in source.split("\n")
            if not line.lstrip().startswith(("%", "!"))
        )
        try:
            ast.parse(source)
        except SyntaxError as error:
            failures.append(f"cell {index}: {error}")

    assert not failures, "notebook cells do not parse:\n" + "\n".join(failures)


if __name__ == "__main__":
    test_every_code_cell_parses()
    print("all notebook code cells parse")
